# Grantmaker settings
foundation_name: The Rwanda Library Project
foundation_tagline: Advancing the adoption of open source technology among progressive funders
grant_application_login: https://www.grantinterface.com/Common/LogOn.aspx?eqs=kw_123456_EXAMPLE

# Social media settings
# Enter the full profile URL (e.g., https://twitter.com/yourfoundation)
profile_twitter: https://twitter.com/examplefdn
profile_facebook: https://facebook.com/the-example-foundation
profile_instagram: https://www.instagram.com/ronanrm_/  # Updated to your Instagram
profile_github: https://github.com/rwandalibraryproject  # Change this to your project's GitHub repo URL

# Site settings
title: The Rwanda Library Project  # Sets the browser tab title
description: >
  RCS’s mission is to empower rural communities in Rwanda through providing access to literacy
  and education through libraries, bridging the educational gap, and bringing knowledge to the
  heart of rural Rwanda.

# Google settings
live: true  # Set to true if you're ready for search engines to index your site

# Jekyll settings
baseurl: ""  # Leave this blank for the root domain (e.g., https://rwandalibraryproject.github.io)
url: https://rwandalibraryproject.github.io  # The live GitHub Pages URL for your site
collections:
  featured-cards:
    output: true
sass:
  sass_dir: assets/css/_sass

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - README.md
  - /images/photoshop-helpers
